### ISSUE TITLE
symboliks None type in x86 (pwnable.kr: "mistake")

### ISSUE THREAD

**Issue by atlas0fd00m** [vivisect/vivisect#243]
Symboliks View for Main, several of the 4 code paths give this:

Traceback (most recent call last):
  File "/OTHER/home/atlas/hacking/git/vivisect/vivisect/vivisect/qt/symboliks.py", line 225, in symPathSelected
    self.rendSymbolikPath()
  File "/OTHER/home/atlas/hacking/git/vivisect/vivisect/vivisect/qt/symboliks.py", line 246, in rendSymbolikPath
    effect.reduce(emu)
  File "/OTHER/home/atlas/hacking/git/vivisect/vivisect/vivisect/symboliks/effects.py", line 110, in reduce
    self.symobj = self.symobj.reduce(emu=emu)
  File "/OTHER/home/atlas/hacking/git/vivisect/vivisect/vivisect/symboliks/common.py", line 210, in reduce
    sym = self.walkTree(doreduce, once=True)
  File "/OTHER/home/atlas/hacking/git/vivisect/vivisect/vivisect/symboliks/common.py", line 324, in walkTree
    newb = cb(path, cur, ctx)
  File "/OTHER/home/atlas/hacking/git/vivisect/vivisect/vivisect/symboliks/common.py", line 208, in doreduce
    return oldkid._reduce(emu=emu)
  File "/OTHER/home/atlas/hacking/git/vivisect/vivisect/vivisect/symboliks/common.py", line 749, in _reduce
    return Const(self.solve(emu=emu), self.getWidth())
  File "/OTHER/home/atlas/hacking/git/vivisect/vivisect/vivisect/symboliks/common.py", line 188, in solve
    ret = self._solve(emu=emu, vals=vals)
  File "/OTHER/home/atlas/hacking/git/vivisect/vivisect/vivisect/symboliks/common.py", line 922, in _solve
    return int(self.oper(v1, v2))
TypeError: 'NoneType' object is not callable

**Comment by rakuy0** [comment]
That's new. But I figured it out. Before when we would reduce a Constraint, it would always just return a new instance of itself with the operands reduced and moved around. Now we're legitimately trying to reduce the operands and it down to a an actual discrete value just like other operators, on a per-operator basis

Normally this isn't a problem. But since there are some symbolik instructions that create UNK constraints, this now becomes a problem, because the reduce function actually tries to call self.oper to see if it can be reduced.

Fix is two part. one is to remove some of the UNKs because they were put there as placeholders for future work, and now the future is here. The other part is adding in a placeholder oper func for UNK and NOUNK that screams about not being implemented and returns a dummy value. And of course tests.

I've got a branch out for it already.
