### ISSUE TITLE
vdb View->Memory Maps crash: trace==None 

### ISSUE THREAD

**Issue by atlas0fd00m** [vivisect/vivisect#260]
when attached to a process ("vdbbin -Q -p ####") and attempting a "View->Memory Maps", vdb crashes with this error:

Traceback (most recent call last):
  File "/OTHER/home/atlas/hacking/git/vivisect/vivisect/vqt/menubuilder.py", line 87, in __call__
    return self.callback(*self.args, **self.kwargs)
  File "/OTHER/home/atlas/hacking/git/vivisect/vivisect/vdb/qt/main.py", line 347, in menuViewMemMaps
    self.vqBuildDockWidget('VQMemoryMapView')
  File "/OTHER/home/atlas/hacking/git/vivisect/vivisect/vqt/application.py", line 128, in vqBuildDockWidget
    obj = cls(*args)
  File "/OTHER/home/atlas/hacking/git/vivisect/vivisect/vtrace/qt.py", line 510, in __init__
    envi_qt_memmap.VQMemoryMapView.__init__(self, trace, parent=parent)
  File "/OTHER/home/atlas/hacking/git/vivisect/vivisect/envi/qt/memorymap.py", line 30, in __init__
    self.vqLoad()
  File "/OTHER/home/atlas/hacking/git/vivisect/vivisect/vtrace/qt.py", line 513, in vqLoad
    if not self.trace.isAttached():
AttributeError: 'NoneType' object has no attribute 'isAttached'
Aborted

**Comment by rakuy0** [comment]
Interesting. Just tried this on a custom built vim I've got, and it works fine. At least on ubuntu linux. But there's a variety of other things that could have aligned to mess yours up.

Do you happen to have the binary that causes it laying around? Any other recreation steps (like what you were doing at the time, did you click on anything else)?

**Comment by rakuy0** [comment]
Poke ^^
