### ISSUE TITLE
vivisect 0.1.0 loops indefinitely

### ISSUE THREAD

**Issue by ankhazam** [vivisect/vivisect#322]
Hi, while using flare-capa 1.3.0 (which uses vivisect 0.1.0) vivisect gets stuck on generating workspace (via viv-utils) for the attached file
[xonotic.zip](https://github.com/vivisect/vivisect/files/5317777/xonotic.zip)
Is there a way to prevent this from happening or introduces a timeout when vivisect aborts the analysis?

Killing the process gives the following stack-trace:
`Traceback (most recent call last):
  File "/usr/local/bin/capa", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/capa/main.py", line 563, in main
    extractor = get_extractor(args.sample, args.format, disable_progress=args.quiet)
  File "/usr/local/lib/python2.7/site-packages/capa/main.py", line 309, in get_extractor
    return get_extractor_py2(path, format, disable_progress=disable_progress)
  File "/usr/local/lib/python2.7/site-packages/capa/main.py", line 282, in get_extractor_py2
    vw = get_workspace(path, format, should_save=False)
  File "/usr/local/lib/python2.7/site-packages/capa/main.py", line 267, in get_workspace
    vw = viv_utils.getWorkspace(path, should_save=should_save)
  File "/usr/local/lib/python2.7/site-packages/viv_utils/__init__.py", line 88, in getWorkspace
    vw.analyze()
  File "/usr/local/lib/python2.7/site-packages/vivisect/__init__.py", line 721, in analyze
    mod.analyze(self)
  File "/usr/local/lib/python2.7/site-packages/vivisect/analysis/generic/entrypoints.py", line 8, in analyze
    vw.processEntryPoints()
  File "/usr/local/lib/python2.7/site-packages/vivisect/__init__.py", line 705, in processEntryPoints
    self.makeFunction(eva)
  File "/usr/local/lib/python2.7/site-packages/vivisect/__init__.py", line 1406, in makeFunction
    realfva = self.cfctx.addEntryPoint(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 284, in addEntryPoint
    self._cb_function(va, {'CallsFrom': calls_from})
  File "/usr/local/lib/python2.7/site-packages/vivisect/base.py", line 751, in _cb_function
    vw.analyzeFunction(fva)
  File "/usr/local/lib/python2.7/site-packages/vivisect/__init__.py", line 734, in analyzeFunction
    fmod.analyzeFunction(self, fva)
  File "/usr/local/lib/python2.7/site-packages/vivisect/analysis/amd64/emulation.py", line 127, in analyzeFunction
    emu.runFunction(fva, maxhit=1)
  File "/usr/local/lib/python2.7/site-packages/vivisect/impemu/emulator.py", line 386, in runFunction
    iscall = self.checkCall(starteip, endeip, op)
  File "/usr/local/lib/python2.7/site-packages/vivisect/impemu/emulator.py", line 188, in checkCall
    ret = self.emumon.apicall(self, op, endeip, api, argv)
  File "/usr/local/lib/python2.7/site-packages/vivisect/impemu/monitor.py", line 211, in apicall
    self.vw.makeFunction(pc, arch=op.iflags & envi.ARCH_MASK)
  File "/usr/local/lib/python2.7/site-packages/vivisect/__init__.py", line 1406, in makeFunction
    realfva = self.cfctx.addEntryPoint(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 284, in addEntryPoint
    self._cb_function(va, {'CallsFrom': calls_from})
  File "/usr/local/lib/python2.7/site-packages/vivisect/base.py", line 751, in _cb_function
    vw.analyzeFunction(fva)
  File "/usr/local/lib/python2.7/site-packages/vivisect/__init__.py", line 734, in analyzeFunction
    fmod.analyzeFunction(self, fva)
  File "/usr/local/lib/python2.7/site-packages/vivisect/analysis/amd64/emulation.py", line 127, in analyzeFunction
    emu.runFunction(fva, maxhit=1)
  File "/usr/local/lib/python2.7/site-packages/vivisect/impemu/emulator.py", line 386, in runFunction
    iscall = self.checkCall(starteip, endeip, op)
  File "/usr/local/lib/python2.7/site-packages/vivisect/impemu/emulator.py", line 188, in checkCall
    ret = self.emumon.apicall(self, op, endeip, api, argv)
  File "/usr/local/lib/python2.7/site-packages/vivisect/impemu/monitor.py", line 211, in apicall
    self.vw.makeFunction(pc, arch=op.iflags & envi.ARCH_MASK)
  File "/usr/local/lib/python2.7/site-packages/vivisect/__init__.py", line 1406, in makeFunction
    realfva = self.cfctx.addEntryPoint(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 278, in addEntryPoint
    calls_from = self.addCodeFlow(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 254, in addCodeFlow
    self.addEntryPoint(fva, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 284, in addEntryPoint
    self._cb_function(va, {'CallsFrom': calls_from})
  File "/usr/local/lib/python2.7/site-packages/vivisect/base.py", line 751, in _cb_function
    vw.analyzeFunction(fva)
  File "/usr/local/lib/python2.7/site-packages/vivisect/__init__.py", line 734, in analyzeFunction
    fmod.analyzeFunction(self, fva)
  File "/usr/local/lib/python2.7/site-packages/vivisect/analysis/amd64/emulation.py", line 127, in analyzeFunction
    emu.runFunction(fva, maxhit=1)
  File "/usr/local/lib/python2.7/site-packages/vivisect/impemu/emulator.py", line 386, in runFunction
    iscall = self.checkCall(starteip, endeip, op)
  File "/usr/local/lib/python2.7/site-packages/vivisect/impemu/emulator.py", line 188, in checkCall
    ret = self.emumon.apicall(self, op, endeip, api, argv)
  File "/usr/local/lib/python2.7/site-packages/vivisect/impemu/monitor.py", line 211, in apicall
    self.vw.makeFunction(pc, arch=op.iflags & envi.ARCH_MASK)
  File "/usr/local/lib/python2.7/site-packages/vivisect/__init__.py", line 1406, in makeFunction
    realfva = self.cfctx.addEntryPoint(va, arch=arch)
  File "/usr/local/lib/python2.7/site-packages/envi/codeflow.py", line 284, in addEntryPoint
    self._cb_function(va, {'CallsFrom': calls_from})
  File "/usr/local/lib/python2.7/site-packages/vivisect/base.py", line 751, in _cb_function
    vw.analyzeFunction(fva)
  File "/usr/local/lib/python2.7/site-packages/vivisect/__init__.py", line 734, in analyzeFunction
    fmod.analyzeFunction(self, fva)
  File "/usr/local/lib/python2.7/site-packages/vivisect/analysis/amd64/emulation.py", line 127, in analyzeFunction
    emu.runFunction(fva, maxhit=1)
  File "/usr/local/lib/python2.7/site-packages/vivisect/impemu/emulator.py", line 370, in runFunction
    self.executeOpcode(op)
  File "/usr/local/lib/python2.7/site-packages/envi/archs/i386/emu.py", line 228, in executeOpcode
    newpc = meth(op)
  File "/usr/local/lib/python2.7/site-packages/envi/archs/i386/emu.py", line 491, in i_add
    self.setOperValue(op, 0, ures)
  File "/usr/local/lib/python2.7/site-packages/envi/__init__.py", line 673, in setOperValue
    return oper.setOperValue(op, self, value)
  File "/usr/local/lib/python2.7/site-packages/envi/archs/i386/disasm.py", line 297, in setOperValue
    emu.writeMemValue(self.getOperAddr(op, emu), val, self.tsize)
  File "/usr/local/lib/python2.7/site-packages/envi/archs/i386/emu.py", line 205, in writeMemValue
    self.writeMemory(addr, bytes)
  File "/usr/local/lib/python2.7/site-packages/vivisect/impemu/emulator.py", line 587, in writeMemory
    return e_mem.MemoryObject.writeMemory(self, va, bytes)
  File "/usr/local/lib/python2.7/site-packages/envi/memory.py", line 472, in writeMemory
    mapdef[3] = mbytes[:offset] + bytes + mbytes[offset+len(bytes):]
KeyboardInterrupt`

**Comment by rakuy0** [comment]
Ah. Fun. I think I know what this is doing. The emulator is running off into lalaland and just spinning through a bunch of bad bytes. Typically when this happens there's some edge case that we just haven't had a chance to take into account, so I'll go over this and see what's missing.

Thanks for sharing the binary! Makes fixing this a lot easier. Do you mind if I end up incorporating this into our unittests?

**Comment by ankhazam** [comment]
Hey,
thanks for the fast response.
As for the binary, I don't mind. Don't know bout the owners though ;)
I've grabbed it from: https://www.xonotic.org/
BR,
Ank

**Comment by rakuy0** [comment]
Should be fixed in v0.2.0
