### ISSUE TITLE
-c/--config option CLI option does not work

### ISSUE THREAD

**Issue by sprout42** [vivisect/vivisect#349]
I was trying to figure out why I couldn't get a vivisect configuration file created and discovered that the `--config` command line option does not save the argument as a string (https://github.com/vivisect/vivisect/blob/master/vivisect/vivbin.py#L52)
```
$ python -m vivisect.vivbin -c ~/.viv -a 
Traceback (most recent call last):
  File "/Users/user/.pyenv/versions/3.8.2/bin/vivbin", line 11, in <module>
    load_entry_point('vivisect==0.2.0', 'console_scripts', 'vivbin')()
  File "/Users/user/.pyenv/versions/3.8.2/Python.framework/Versions/3.8/lib/python3.8/site-packages/vivisect/vivbin.py", line 59, in main
    vw = viv_cli.VivCli(confdir=args.config, autosave=args.autosave)
  File "/Users/user/.pyenv/versions/3.8.2/Python.framework/Versions/3.8/lib/python3.8/site-packages/vivisect/cli.py", line 53, in __init__
    vivisect.VivWorkspace.__init__(self, **kwargs)
  File "/Users/user/.pyenv/versions/3.8.2/Python.framework/Versions/3.8/lib/python3.8/site-packages/vivisect/__init__.py", line 81, in __init__
    self.vivhome = os.path.abspath(cfgdir)
  File "/Users/user/.pyenv/versions/3.8.2/Python.framework/Versions/3.8/lib/python3.8/posixpath.py", line 374, in abspath
    path = os.fspath(path)
TypeError: expected str, bytes or os.PathLike object, not bool
```

**Comment by rakuy0** [comment]
Thanks! Should be easy to fix. I'll have it up after I deal with #348 , which I'm waist deep in right now.
