### ISSUE TITLE
Exception: Machine aa64 is not supported for PE!

### ISSUE THREAD

**Issue by williballenthin** [vivisect/vivisect#417]
```
> python vivisect/vivbin.py --bulk samples/004e32a0f3610532cf08ce0ca4ee3ce2628faa0a143b732151706a8b7fda0df1                                                                            fix-415?
Traceback (most recent call last):
  File "vivisect/vivbin.py", line 144, in <module>
    main()
  File "vivisect/vivbin.py", line 98, in main
    vw.loadFromFile(fname, fmtname=args.parsemod)
  File "/home/user/code/vivisect/vivisect/__init__.py", line 2725, in loadFromFile
    fname = mod.parseFile(self, filename=filename, baseaddr=baseaddr)
  File "/home/user/code/vivisect/vivisect/parsers/pe.py", line 37, in parseFile
    return loadPeIntoWorkspace(vw, pe, filename=filename, baseaddr=baseaddr)
  File "/home/user/code/vivisect/vivisect/parsers/pe.py", line 90, in loadPeIntoWorkspace
    raise Exception("Machine %.4x is not supported for PE!" % mach)
Exception: Machine aa64 is not supported for PE!
```

would like a more specific exception that can be handled and rendered by a client application.

source: https://github.com/fireeye/capa/issues/702
sample: https://www.virustotal.com/gui/file/004e32a0f3610532cf08ce0ca4ee3ce2628faa0a143b732151706a8b7fda0df1/details

**Comment by rakuy0** [comment]
Aye, more specific exceptions are good :+1:
