### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zero

### ISSUE THREAD

**Issue by williballenthin** [vivisect/vivisect#419]
```
> python vivisect/vivbin.py --bulk samples/007ab1f8eb4ef62e9ea7607363dbacd205c7e89b159e5db554cfebef308a4c42                                                                          1 fix-417?
Traceback (most recent call last):
  File "vivisect/vivbin.py", line 144, in <module>
    main()
  File "vivisect/vivbin.py", line 98, in main
    vw.loadFromFile(fname, fmtname=args.parsemod)
  File "/home/user/code/vivisect/vivisect/__init__.py", line 2725, in loadFromFile
    fname = mod.parseFile(self, filename=filename, baseaddr=baseaddr)
  File "/home/user/code/vivisect/vivisect/parsers/pe.py", line 38, in parseFile
    return loadPeIntoWorkspace(vw, pe, filename=filename, baseaddr=baseaddr)
  File "/home/user/code/vivisect/vivisect/parsers/pe.py", line 181, in loadPeIntoWorkspace
    secrem = len(header) % secalign
ZeroDivisionError: integer division or modulo by zero
```

this file appears corrupt. still, it would be nice for a specific exception to be raised, such as `CorruptFile("invalid section alignment")`

source: https://github.com/fireeye/capa/issues/704

**Comment by williballenthin** [comment]
clearly corrupt file: 

![image](https://user-images.githubusercontent.com/156560/128798928-68370fb6-3db7-4906-8625-26d02f72b232.png)

**Comment by rakuy0** [comment]
Similar to the others, I like more specific exceptions :+1:
