### ISSUE TITLE
struct.error: unpack requires a buffer of 4 bytes

### ISSUE THREAD

**Issue by williballenthin** [vivisect/vivisect#421]
```
> python vivisect/vivbin.py --bulk samples/021aa79573478322e1e3f419f20be9c7543d9754d99cad9d6499e7f43596a068                                                                            fix-415?
Traceback (most recent call last):
  File "vivisect/vivbin.py", line 144, in <module>
    main()
  File "vivisect/vivbin.py", line 98, in main
    vw.loadFromFile(fname, fmtname=args.parsemod)
  File "/home/user/code/vivisect/vivisect/__init__.py", line 2725, in loadFromFile
    fname = mod.parseFile(self, filename=filename, baseaddr=baseaddr)
  File "/home/user/code/vivisect/vivisect/parsers/pe.py", line 37, in parseFile
    return loadPeIntoWorkspace(vw, pe, filename=filename, baseaddr=baseaddr)
  File "/home/user/code/vivisect/vivisect/parsers/pe.py", line 523, in loadPeIntoWorkspace
    pebytes = subpe.readAtOffset(0, subpe.getFileSize())
  File "/home/user/code/vivisect/PE/carve.py", line 68, in getFileSize
    for sec in self.getSections():
  File "/home/user/code/vivisect/PE/__init__.py", line 489, in getSections
    return self.sections
  File "/home/user/code/vivisect/PE/__init__.py", line 1208, in __getattr__
    self.parseSections()
  File "/home/user/code/vivisect/PE/__init__.py", line 709, in parseSections
    s.vsParse(sbytes[:secsize])
  File "/home/user/code/vivisect/vstruct/__init__.py", line 167, in vsParse
    offset = fobj.vsParse(sbytes, offset=offset)
  File "/home/user/code/vivisect/vstruct/primitives.py", line 186, in vsParse
    self._vs_value = struct.unpack(self._vs_fmt, b)[0]
struct.error: unpack requires a buffer of 4 bytes
```

this file appears corrupt. still, it would be nice for a specific exception to be raised, such as `CorruptFile("truncated section data")`.

source: https://github.com/fireeye/capa/issues/705

**Comment by rakuy0** [comment]
:+1:
