### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by williballenthin** [vivisect/vivisect#425]
```
> python vivisect/vivbin.py --bulk samples/0a50a0582cf414bae644be1ae2164183c1549e869f0ef8ea8d6b3002a098dd0b                                                                            working?
Traceback (most recent call last):
  File "vivisect/vivbin.py", line 144, in <module>
    main()
  File "vivisect/vivbin.py", line 98, in main
    vw.loadFromFile(fname, fmtname=args.parsemod)
  File "/home/user/code/vivisect/vivisect/__init__.py", line 2725, in loadFromFile
    fname = mod.parseFile(self, filename=filename, baseaddr=baseaddr)
  File "/home/user/code/vivisect/vivisect/parsers/pe.py", line 38, in parseFile
    return loadPeIntoWorkspace(vw, pe, filename=filename, baseaddr=baseaddr)
  File "/home/user/code/vivisect/vivisect/parsers/pe.py", line 128, in loadPeIntoWorkspace
    dllname = pe.getDllName()
  File "/home/user/code/vivisect/PE/__init__.py", line 457, in getDllName
    return rawname.split(b'\x00')[0].decode('utf-8')
AttributeError: 'NoneType' object has no attribute 'split'
```

the DLL name pointer is invalid so it fails to read data and the `None` cannot be split.

**Comment by rakuy0** [comment]
:+1:
