### ISSUE TITLE
struct.error: unpack requires a buffer of 32754 bytes

### ISSUE THREAD

**Issue by williballenthin** [vivisect/vivisect#427]
```
> python vivisect/vivbin.py --bulk samples/526ff9827564a4464da55accdbaa060655dbe831487ebb663230e454d21b81b7                     
Traceback (most recent call last):
  File "vivisect/vivbin.py", line 144, in <module>
    main()
  File "vivisect/vivbin.py", line 98, in main
    vw.loadFromFile(fname, fmtname=args.parsemod)
  File "/home/user/code/vivisect/vivisect/__init__.py", line 2725, in loadFromFile
    fname = mod.parseFile(self, filename=filename, baseaddr=baseaddr)
  File "/home/user/code/vivisect/vivisect/parsers/pe.py", line 38, in parseFile
    return loadPeIntoWorkspace(vw, pe, filename=filename, baseaddr=baseaddr)
  File "/home/user/code/vivisect/vivisect/parsers/pe.py", line 349, in loadPeIntoWorkspace
    for rva, rtype in pe.getRelocations():
  File "/home/user/code/vivisect/PE/__init__.py", line 914, in getRelocations
    return self.relocations
  File "/home/user/code/vivisect/PE/__init__.py", line 1216, in __getattr__
    self.parseRelocations()
  File "/home/user/code/vivisect/PE/__init__.py", line 948, in parseRelocations
    rels = struct.unpack("<%dH" % relcnt, relbytes[8:chunksize])
struct.error: unpack requires a buffer of 32754 bytes
```

i think the file is corrupt. still, would like to see a more specific error that can be handled and rendered.

source: https://github.com/fireeye/capa/issues/713

**Comment by williballenthin** [comment]
another bug `relcnt` is a float here: https://github.com/vivisect/vivisect/blob/6de41d2f238ec4531ae0f85b57ea9d11ac8d5f9e/PE/__init__.py#L935
