### ISSUE TITLE
windows platformDetach reports TypeError

### ISSUE THREAD

**Issue by midgen42** [vivisect/vivisect#429]
```
Loading Binary: C:\\Windows\System32\ole32.dll
Loading Binary: C:\\Windows\System32\dwmapi.dll
New Thread: 11832
Thread: 11832 NOTIFY_BREAK
vdb > quit
Detached from 7140
Traceback (most recent call last):
  File "C:\Vivisect\vdb\__init__.py", line 1509, in do_quit
    self.trace.detach()
  File "C:\Vivisect\vtrace\__init__.py", line 311, in detach
    self.platformDetach()
  File "C:\Vivisect\vtrace\platforms\base.py", line 890, in trfunc
    raise ret
  File "C:\Vivisect\vtrace\platforms\base.py", line 924, in run
    queue.put(meth(*args, **kwargs))
  File "C:\Vivisect\vtrace\platforms\win32.py", line 1438, in platformDetach
    kernel32.CloseHandle(phandle)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

Exception during quit (may need: quit force): argument 1: <class 'TypeError'>: wrong type
vdb >
```

**Comment by midgen42** [comment]
need to move `self.phandle = None` after `phandle = self.phandle`  to prevent the call `kernel32.CloseHandle(phandle)` from failing

**Comment by rakuy0** [comment]
Yea. @atlas0fd00m and I just found this the other day. Ends up being the result of some git conflicts that didn't get resolved properly. We'll get this sorted out shortly, but thanks for letting us know!

**Comment by atlas0fd00m** [comment]
good catch and thank you for pointing it out!  yup, this is part of the current Vtrace PR we're working on.
