### ISSUE TITLE
tests do not pass on Windows

### ISSUE THREAD

**Issue by williballenthin** [vivisect/vivisect#430]
In summary:
  - `ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type` in `platformDetach`
  - `Exception: Unsupported Expression (symbolik width index)` in `astToSymboliks`
  - `KeyError: '.rsrc'` in `test_mimikatz_segments` and `test_firefox_segments`
  - `AssertionError: Items in the second set but not the first:` in `test_memorymaps_basicperms`
  - `vtrace.PlatformException: Win32 Error kernel32.WriteProcessMemory failed: 998`
  - `AssertionError: Tuples differ` in `test_basic_apis`

There are some other errors in cobra and gui that I've ignored because I'm not running this as admin nor with pyqt.

I'd recommend running these tests via CI against all PRs and other commits. We have such a setup for capa that runs all tests taking 15mins each against (linux, mac, win) by (py3.6, py3.9). We do this all on GH Action free tier without any trouble. May you can adapt our config for more thorough testing of vivisect? 

https://github.com/fireeye/capa/blob/master/.github/workflows/tests.yml

```
======================================================================
ERROR: test_cobra_authentication (cobra.tests.testbasic.CobraBasicTest)
----------------------------------------------------------------------
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions
======================================================================
ERROR: test_cobra_msgpack (cobra.tests.testbasic.CobraBasicTest)
----------------------------------------------------------------------
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

======================================================================
ERROR: test_cobra_proxy (cobra.tests.testbasic.CobraBasicTest)
----------------------------------------------------------------------
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

======================================================================
ERROR: test_cobra_refcount (cobra.tests.testbasic.CobraBasicTest)
----------------------------------------------------------------------
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

======================================================================
ERROR: test_cobra_shadowauth (cobra.tests.testbasic.CobraBasicTest)
----------------------------------------------------------------------
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

======================================================================
ERROR: test_cobra_newobj (cobra.tests.testnewobj.CobraNewObjTest)
----------------------------------------------------------------------
OSError: [WinError 10013] An attempt was made to access a socket in a way forbidden by its access permissions

======================================================================
ERROR: test_emu_lockstep (envi.tests.test_emu_lockstep.LockStepTest)
----------------------------------------------------------------------
Traceback (most recent call last):
...
  File "C:\Users\user\Downloads\vivisect\vtrace\platforms\win32.py", line 1438, in platformDetach
    kernel32.CloseHandle(phandle)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

======================================================================
ERROR: test_vdb_stalker (vdb.tests.teststalker.VdbStalkerTest)
----------------------------------------------------------------------
Traceback (most recent call last):
...
  File "C:\Users\user\Downloads\vivisect\vtrace\platforms\win32.py", line 1438, in platformDetach
    kernel32.CloseHandle(phandle)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

======================================================================
ERROR: test_symboliks_reduce_op_and (vivisect.symboliks.tests.test_reduce.TestReduceCase)
----------------------------------------------------------------------
Traceback (most recent call last):
...
  File "C:\Users\user\Downloads\vivisect\vivisect\symboliks\expression.py", line 135, in astToSymboliks
    raise Exception('Unsupported Expression (symbolik width index)')
Exception: Unsupported Expression (symbolik width index)

======================================================================
ERROR: test_mimikatz_segments (vivisect.tests.testpe.PETests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\user\Downloads\vivisect\vivisect\tests\testpe.py", line 501, in test_mimikatz_segments
    self.assertEqual(ans[sname][0], sva)
KeyError: '.rsrc'

======================================================================
ERROR: test_firefox_segments (vivisect.tests.testvivisect.VivisectTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\user\Downloads\vivisect\vivisect\tests\testvivisect.py", line 830, in test_firefox_segments
    self.assertEqual(ans[sname][0], sva)
KeyError: '.rsrc'

======================================================================
ERROR: vqt.tests.testmenubuilder (unittest.loader._FailedTest)
----------------------------------------------------------------------
ModuleNotFoundError: No module named 'PyQt5'


======================================================================
ERROR: vstruct.qt (unittest.loader._FailedTest)
----------------------------------------------------------------------
ModuleNotFoundError: No module named 'PyQt5'


======================================================================
ERROR: test_baselib (vtrace.tests.test_expressions.VtraceExpressionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
...
  File "C:\Users\user\Downloads\vivisect\vtrace\platforms\win32.py", line 1438, in platformDetach
    kernel32.CloseHandle(phandle)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

======================================================================
ERROR: test_vtrace_sym (vtrace.tests.test_expressions.VtraceExpressionTest)
----------------------------------------------------------------------
Traceback (most recent call last):
...
  File "C:\Users\user\Downloads\vivisect\vtrace\platforms\win32.py", line 1438, in platformDetach
    kernel32.CloseHandle(phandle)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

======================================================================
ERROR: test_vtrace_breakpoint (vtrace.tests.testbasic.VtraceBasicExecTest)
----------------------------------------------------------------------
Traceback (most recent call last):
...
  File "C:\Users\user\Downloads\vivisect\vtrace\platforms\win32.py", line 1438, in platformDetach
    kernel32.CloseHandle(phandle)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

======================================================================
ERROR: test_vtrace_exename (vtrace.tests.testbasic.VtraceBasicExecTest)
----------------------------------------------------------------------
Traceback (most recent call last):
...
  File "C:\Users\user\Downloads\vivisect\vtrace\platforms\win32.py", line 1438, in platformDetach
    kernel32.CloseHandle(phandle)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

======================================================================
ERROR: test_vtrace_getregisters (vtrace.tests.testbasic.VtraceBasicExecTest)
----------------------------------------------------------------------
Traceback (most recent call last):
...
  File "C:\Users\user\Downloads\vivisect\vtrace\platforms\win32.py", line 1438, in platformDetach
    kernel32.CloseHandle(phandle)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

======================================================================
ERROR: test_vtrace_mmaps (vtrace.tests.testbasic.VtraceBasicExecTest)
----------------------------------------------------------------------
Traceback (most recent call last):
...
  File "C:\Users\user\Downloads\vivisect\vtrace\platforms\win32.py", line 1438, in platformDetach
    kernel32.CloseHandle(phandle)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

======================================================================
ERROR: test_vtrace_setregisters (vtrace.tests.testbasic.VtraceBasicExecTest)
----------------------------------------------------------------------
Traceback (most recent call last):
...
  File "C:\Users\user\Downloads\vivisect\vtrace\platforms\win32.py", line 1438, in platformDetach
    kernel32.CloseHandle(phandle)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

======================================================================
ERROR: test_vtrace_breakpoint (vtrace.tests.testbasic.VtraceBasicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
...
  File "C:\Users\user\Downloads\vivisect\vtrace\platforms\win32.py", line 1438, in platformDetach
    kernel32.CloseHandle(phandle)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

======================================================================
ERROR: test_vtrace_exename (vtrace.tests.testbasic.VtraceBasicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
...
  File "C:\Users\user\Downloads\vivisect\vtrace\platforms\win32.py", line 1438, in platformDetach
    kernel32.CloseHandle(phandle)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

======================================================================
ERROR: test_vtrace_getregisters (vtrace.tests.testbasic.VtraceBasicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
...
  File "C:\Users\user\Downloads\vivisect\vtrace\platforms\win32.py", line 1438, in platformDetach
    kernel32.CloseHandle(phandle)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

======================================================================
ERROR: test_vtrace_mmaps (vtrace.tests.testbasic.VtraceBasicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
...
  File "C:\Users\user\Downloads\vivisect\vtrace\platforms\win32.py", line 1438, in platformDetach
    kernel32.CloseHandle(phandle)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

======================================================================
ERROR: test_vtrace_setregisters (vtrace.tests.testbasic.VtraceBasicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
...
  File "C:\Users\user\Downloads\vivisect\vtrace\platforms\win32.py", line 1438, in platformDetach
    kernel32.CloseHandle(phandle)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

======================================================================
ERROR: test_emulatorFromTrace (vtrace.tests.tests_envitools.EnvitoolsTests)
----------------------------------------------------------------------
Traceback (most recent call last):
...
  File "C:\Users\user\Downloads\vivisect\vtrace\platforms\win32.py", line 1438, in platformDetach
    kernel32.CloseHandle(phandle)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

======================================================================
ERROR: test_vtrace_threads (vtrace.tests.testthread.VtraceThreadTest)
----------------------------------------------------------------------
Traceback (most recent call last):
...
  File "C:\Users\user\Downloads\vivisect\vtrace\platforms\win32.py", line 1438, in platformDetach
    kernel32.CloseHandle(phandle)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type

======================================================================
ERROR: test_vtrace_writemem (vtrace.tests.testwritemem.VtraceWritememTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\user\Downloads\vivisect\vtrace\tests\testwritemem.py", line 22, in test_vtrace_writemem
    self.trace.writeMemory(addr, testbuf)
  File "C:\Users\user\Downloads\vivisect\vtrace\__init__.py", line 526, in writeMemory
    self.platformWriteMemory(int(address), bytez)
  File "C:\Users\user\Downloads\vivisect\vtrace\platforms\win32.py", line 1526, in platformWriteMemory
    raiseWin32Error("kernel32.WriteProcessMemory")
  File "C:\Users\user\Downloads\vivisect\vtrace\platforms\win32.py", line 1203, in raiseWin32Error
    raise vtrace.PlatformException("Win32 Error %s failed: %s" % (name,kernel32.GetLastError()))
vtrace.PlatformException: Win32 Error kernel32.WriteProcessMemory failed: 998

======================================================================
FAIL: test_memorymaps_basicperms (vivisect.tests.testmalware.MalwareTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\user\Downloads\vivisect\vivisect\tests\testmalware.py", line 36, in test_memorymaps_basicperms
    self.assertEqual(maps, set(vw.getMemoryMaps()))
AssertionError: Items in the second set but not the first:
(269000704, 436, 4, '0e25aa791c9119108af073bc9e9d0fa2')

======================================================================
FAIL: test_basic_apis (vivisect.tests.testvivisect.VivisectTest)
Test a bunch of the simpler workspace APIs
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\user\Downloads\vivisect\vivisect\tests\testvivisect.py", line 240, in test_basic_apis
    self.assertEqual(locdist, ans[loctype])
AssertionError: Tuples differ: ('Undefined', 0, 259593, 44) != ('Undefined', 0, 53337, 14)

First differing element 2:
259593
53337

- ('Undefined', 0, 259593, 44)
?                  - ---   ^

+ ('Undefined', 0, 53337, 14)
?                    +++  ^


----------------------------------------------------------------------
Ran 353 tests in 473.966s

FAILED (failures=2, errors=28, skipped=2)
```

```
(env) PS C:\Users\user\Downloads\vivisect> git log -1
commit 6453b76b9946239ef7603294d6eac2ac3f151837 (HEAD -> master, origin/master, origin/HEAD)
Author: James Gross <45212823+rakuy0@users.noreply.github.com>
Date:   Tue Aug 10 14:40:57 2021 -0400

    Change amd64 symboliks callconv class declaration (#413)

    Reorder Amd64 symboliks callconv declaration to avoid exceptions
(env) PS C:\Users\user\Downloads\vivisect> python -V
Python 3.8.5
(env) PS C:\Users\user\Downloads\vivisect> pip freeze
cxxfilt==0.2.2
msgpack==1.0.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.20
-e git+ssh://git@github.com/vivisect/vivisect.git@6453b76b9946239ef7603294d6eac2ac3f151837#egg=vivisect
```

**Comment by williballenthin** [comment]
on linux, things look *better*:

```
======================================================================
ERROR: test_symboliks_reduce_op_and (vivisect.symboliks.tests.test_reduce.TestReduceCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/user/code/vivisect/vivisect/symboliks/tests/test_reduce.py", line 34, in test_symboliks_reduce_op_and
    self.assertReduce('foo[5] & 0', '0')
  File "/home/user/code/vivisect/vivisect/symboliks/tests/test_reduce.py", line 11, in assertReduce
    sym1 = symexp(s1).reduce(foo=True)
  File "/home/user/code/vivisect/vivisect/symboliks/expression.py", line 40, in symexp
    return p.parseExpression(expr)
  File "/home/user/code/vivisect/vivisect/symboliks/expression.py", line 67, in parseExpression
    return self.astToSymboliks(a.body[0])
  File "/home/user/code/vivisect/vivisect/symboliks/expression.py", line 90, in astToSymboliks
    return self.astToSymboliks(a.value)
  File "/home/user/code/vivisect/vivisect/symboliks/expression.py", line 93, in astToSymboliks
    left = self.astToSymboliks(a.left)
  File "/home/user/code/vivisect/vivisect/symboliks/expression.py", line 135, in astToSymboliks
    raise Exception('Unsupported Expression (symbolik width index)')
Exception: Unsupported Expression (symbolik width index)

----------------------------------------------------------------------
Ran 353 tests in 382.084s

FAILED (errors=1, skipped=3)
```

**Comment by rakuy0** [comment]
`I'd recommend running these tests via CI against all PRs and other commits`
* So the original reason we did this is because back when we migrated off of travis, GH Actions and Circle seemed comparable in terms of how much time we got, and it wasn't enough to support more than a handful of windows runs (which wasn't particular worth it to setup if we were only going to get like 5 runs total). Is that no longer the case?
* And just so I can bound this for my own testing, most of this is specifc to py3.8 correct?

**Comment by atlas0fd00m** [comment]
bless you, @williballenthin !  thank you for the feedback and insight and PRs to improve Viv!  your help is very much appreciated!

@

**Comment by atlas0fd00m** [comment]
some of these are fixed in PR's we're working to get merged in.
some of these are installation problems (we can't have the unittests install pyqt5, for example.
some of these are new and need some attention!
one or two of these look like "ghost in the box" issues i can see on one of my dev boxes where i've changed something ( i know not what) and tests fail that i cannot explain (even tho the same installation on a diff system works fine and unittests work on CI)


we'll def kill the `    kernel32.CloseHandle(phandle)` bug soon.

**Comment by williballenthin** [comment]
thank you all!

> Is that no longer the case?

I can only speak from my experience, and I have a suspicion that GH Actions doesn't track their usage very closely, so things have the potential to change...

We run our full test suite against all pushes to master & PRs. For your amusement, the testing history is here: https://github.com/fireeye/capa/actions/workflows/tests.yml It should illustrate that we run up to a few dozen full workflows per week, ranging from 30-90mins each. I'm not really sure how to check our quota, and tbh, I'm not sure I want to know. But, I can confirm it works well and we haven't had any trouble.

I recently backported our capa setup to floss and it took maybe 15 minutes. I hope you could do the same with vivisect (only if you want). The key details are here: https://github.com/fireeye/capa/blob/master/.github/workflows/tests.yml#L66-L90 Although 3.6 is old, we keep that around as its the last version to run on Win7. 

> most of this is specifc to py3.8 correct?

I have no idea - 3.8 is just what I had handy on my laptop. I haven't had a chance to triage the failures but I did want to report them while I had the details handy.

**Comment by rakuy0** [comment]
Ah, thank you @williballenthin. Wouldn't have realized any of this without you.

`It should illustrate that we run up to a few dozen full workflows per week`
That is promising. It seems like they've been putting a lot of work into it. I'll talk with atlas about it, but it does seem tempting if it can support you guys like that (especially on the windows front).

`3.8 is just what I had handy on my laptop`
That's fair. 3.9 is what's handy on mine, and why I probably didn't notice any of this. But it seems like a lot of it was <3.9 (they deprecated some things in 3.9 and swapped around some types). That's more so I know what things I need to test before submitting a PR.

But hopefully we can resolve this in a couple days, and maybe cut a release too :smile:

**Comment by atlas0fd00m** [comment]
is this resolved?

**Comment by williballenthin** [comment]
no, tests do not pass under Windows:

```
======================================================================
ERROR: test_do_cmds (envi.tests.test_cli.EnviCliTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\user\Documents\code\vivisect\envi\tests\test_cli.py", line 98, in test_do_cmds
    ecli.do_memdump('0x41410001 /tmp/foo40 20')
  File "C:\Users\user\Documents\code\vivisect\envi\cli.py", line 768, in do_memdump
    with open(fname, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/foo40'
======================================================================
ERROR: test_emu_lockstep (envi.tests.test_emu_lockstep.LockStepTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\user\Documents\code\vivisect\envi\tests\test_emu_lockstep.py", line 143, in test_emu_lockstep
    lock.stepi(stepcount)
  File "C:\Users\user\Documents\code\vivisect\envi\tests\test_emu_lockstep.py", line 89, in stepi
    self.cmpregs(op1, op2)
  File "C:\Users\user\Documents\code\vivisect\envi\tests\test_emu_lockstep.py", line 104, in cmpregs
    raise Exception('LockStep: emu 0x%.8x %s %s=0x%.8x | trace 0x%.8x %s %s=0x%.8x' % (emuop.va, repr(emuop), regname, regval, traceop.va, repr(traceop), regname, traceval))
Exception: LockStep: emu 0x7ffce01a9527 shr cx,8 eflags=0x00000203 | trace 0x7ffce01a9527 shr cx,8 eflags=0x00000a03
======================================================================
FAIL: test_symbol (vtrace.tests.test_symcache.VtraceSymbolTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\user\Documents\code\vivisect\vtrace\tests\test_symcache.py", line 12, in test_symbol
    self.assertGreater(len(symlist), 1000)
AssertionError: 37 not greater than 1000
----------------------------------------------------------------------
Ran 308 tests in 19.727s

FAILED (failures=1, errors=4, skipped=19)
```

**Comment by atlas0fd00m** [comment]
is this resolved?
