### ISSUE TITLE
Exception: Invalid String Size: -1

### ISSUE THREAD

**Issue by williballenthin** [vivisect/vivisect#433]
```
> python ~/code/vivisect/vivisect/vivbin.py --bulk samples/538f5401738b524c299b74c5cbba34bc070e18a642f3abfca408e15d6de03897
Traceback (most recent call last):
  File "/home/user/code/vivisect/vivisect/vivbin.py", line 144, in <module>
    main()
  File "/home/user/code/vivisect/vivisect/vivbin.py", line 98, in main
    vw.loadFromFile(fname, fmtname=args.parsemod)
  File "/home/user/code/vivisect/vivisect/__init__.py", line 2725, in loadFromFile
    fname = mod.parseFile(self, filename=filename, baseaddr=baseaddr)
  File "/home/user/code/vivisect/vivisect/parsers/pe.py", line 38, in parseFile
    return loadPeIntoWorkspace(vw, pe, filename=filename, baseaddr=baseaddr)
  File "/home/user/code/vivisect/vivisect/parsers/pe.py", line 433, in loadPeIntoWorkspace
    vw.makeString(rva+baseaddr)
  File "/home/user/code/vivisect/vivisect/__init__.py", line 2136, in makeString
    raise Exception("Invalid String Size: %d" % size)
Exception: Invalid String Size: -1
```

when there is an invalid forwarder in the PE loader
https://github.com/vivisect/vivisect/blob/ad6fbba99a6e82ddefbbf8137e7e4e450fe5fc11/vivisect/parsers/pe.py#L433

`asciiStringSize` returns -1 when it cannot find the NULL terminator.
https://github.com/vivisect/vivisect/blob/ad6fbba99a6e82ddefbbf8137e7e4e450fe5fc11/vivisect/__init__.py#L2265

so `makeString` gets unhappy
https://github.com/vivisect/vivisect/blob/master/vivisect/__init__.py#L2136

**Comment by williballenthin** [comment]
i'll submit a PR shortly

**Comment by williballenthin** [comment]
turns out the forwarder is not invalid; rather, viv incorrectly returns data from the end of a section (doesn't pad/align the section maybe? or read is truncated? not sure yet). will report and triage this separately.

**Comment by williballenthin** [comment]
#436 fixes the underlying section alignment issue. #437 will fix the exception raised here.
