### ISSUE TITLE
TypeError: a bytes-like object is required, not 'NoneType'

### ISSUE THREAD

**Issue by williballenthin** [vivisect/vivisect#438]
```
> python ~/code/vivisect/vivisect/vivbin.py --bulk samples/471ce36855fec6b44398b9b1e3cfb9e74b122fb2cc20fdf6603ebda39f86dddf                                                           1
Traceback (most recent call last):
  File "/home/user/code/vivisect/vivisect/vivbin.py", line 144, in <module>
    main()
  File "/home/user/code/vivisect/vivisect/vivbin.py", line 98, in main
    vw.loadFromFile(fname, fmtname=args.parsemod)
  File "/home/user/code/vivisect/vivisect/__init__.py", line 2725, in loadFromFile
    fname = mod.parseFile(self, filename=filename, baseaddr=baseaddr)
  File "/home/user/code/vivisect/vivisect/parsers/pe.py", line 45, in parseFile
    return loadPeIntoWorkspace(vw, pe, filename=filename, baseaddr=baseaddr)
  File "/home/user/code/vivisect/vivisect/parsers/pe.py", line 395, in loadPeIntoWorkspace
    for rva, lname, iname in pe.getDelayImports():
  File "/home/user/code/vivisect/PE/__init__.py", line 479, in getDelayImports
    return self.delayImports
  File "/home/user/code/vivisect/PE/__init__.py", line 1212, in __getattr__
    self.parseDelayImports()
  File "/home/user/code/vivisect/PE/__init__.py", line 836, in parseDelayImports
    self.delayImports = self.parseImportTable(x, irva, is_imports=False)
  File "/home/user/code/vivisect/PE/__init__.py", line 879, in parseImportTable
    ibn_rva = self.readPointerAtRva(imp_by_name+arrayoff)
  File "/home/user/code/vivisect/PE/__init__.py", line 765, in readPointerAtRva
    return self.readPointerAtOffset(off)
  File "/home/user/code/vivisect/PE/__init__.py", line 761, in readPointerAtOffset
    return struct.unpack(fmt, self.readAtOffset(off, self.psize))[0]
TypeError: a bytes-like object is required, not 'NoneType'
```

looks like an issue with parseDelayImports

**Comment by williballenthin** [comment]
will triage and report back here.

**Comment by williballenthin** [comment]
trying to read the the following:
```
imp_by_name: 0x4dcbb0 
arrayoff: 0x0
imp_by_name+arrayoff: 0x4dcbb0
```

![image](https://user-images.githubusercontent.com/156560/130150434-f3ff62ec-eaf1-4020-abe0-2b1ed7e0a178.png)
![image](https://user-images.githubusercontent.com/156560/130150465-9581d33e-49e4-4d65-b9ee-0a0cb3031752.png)

**Comment by williballenthin** [comment]
this is a known weird fact about delayed imports: they *usually* contain an RVA but they *may* contain a VA (esp from VS6): https://reverseengineering.stackexchange.com/a/16266/17194

so, when processing delayed imports, we should try to recognize when dealing with VAs rather than RVAs and take appropriate action.

**Comment by williballenthin** [comment]
also a bug: this is a large binary (mapped size at least 0x685de8) and this size is larger than its base address (0x401000) so a naive "is potential RVA < base address?" doesn't work here.
