### ISSUE TITLE
ELF regression: read exception in symbol table parsing

### ISSUE THREAD

**Issue by williballenthin** [vivisect/vivisect#443]
```
> vivbin -B ~/code/capa-pub/tests/data/7351f8a40c5450557b24622417fc478d.elf_  
Traceback (most recent call last):
  File "/home/user/code/vivisect/env/bin/vivbin", line 11, in <module>
    load_entry_point('vivisect', 'console_scripts', 'vivbin')()
  File "/home/user/code/vivisect/vivisect/vivbin.py", line 98, in main
    vw.loadFromFile(fname, fmtname=args.parsemod)
  File "/home/user/code/vivisect/vivisect/__init__.py", line 2728, in loadFromFile
    fname = mod.parseFile(self, filename=filename, baseaddr=baseaddr)
  File "/home/user/code/vivisect/vivisect/parsers/elf.py", line 30, in parseFile
    return loadElfIntoWorkspace(vw, elf, filename=filename, baseaddr=baseaddr)
  File "/home/user/code/vivisect/vivisect/parsers/elf.py", line 525, in loadElfIntoWorkspace
    valu = vw.readMemoryPtr(sva)
  File "/home/user/code/vivisect/envi/memory.py", line 181, in readMemoryPtr
    return self.readMemValue(va, self.imem_psize)
  File "/home/user/code/vivisect/envi/memory.py", line 170, in readMemValue
    raise Exception("Read gave wrong length at va: 0x%.8x (wanted %d got %d)" % (addr, size, len(bytes)))
Exception: Read gave wrong length at va: 0x00409c08 (wanted 8 got 4)
```

only started seeing this in the v1.0.4 release

sample: https://github.com/fireeye/capa-testfiles/blob/master/7351f8a40c5450557b24622417fc478d.elf_
this is our *one* ELF test file for capa, so that has me a bit worried about how thoroughly regression tested the new ELF changes are. hopefully its just a random one off :-)

**Comment by williballenthin** [comment]
`sva` log:
![image](https://user-images.githubusercontent.com/156560/130530837-cf2582c7-2669-4ad5-bd38-ff53341cfef0.png)

exception at read pointer from 0x409c08

**Comment by williballenthin** [comment]
its weird that `readMemoryPtr` can both return None and raise an exception:

![image](https://user-images.githubusercontent.com/156560/130531930-5a693e0b-2dbb-43b5-a56c-6534ba89135b.png)
