### ISSUE TITLE
UnicodeDecodeError on PE section names

### ISSUE THREAD

**Issue by mmaps** [vivisect/vivisect#499]
There is a UnicodeDecodeError in vstruct when getting a PE file's section name that has non-ascii characters. To fix this, I'd like to see if Vivisect would be open to a possible breaking change where section names are returned as bytes instead of strings?

To repro the issue, run this script on a file with a non-ascii character in the section name. I created [a test case here](https://github.com/mmaps/HelloSection).
```
import PE
import sys
pe_fd = open(sys.argv[1])
pe = PE.PE(pe_fd)
[s.Name for s in pe.getSections()]
```
The first fix I tried was a try/except UnicodeDecodeError in VStruct.__getattr__. However, I'm not sure if this is acceptable because you will get back a mixed bag of types determined by UnicodeDecodeErrors:
```
420             try:
421                 return r.vsGetValue() # str
422             except UnicodeDecodeError:
423                 return r.vsEmit() # bytes
```
The mixed bag:
```
>>> [s.Name for s in pe.getSections()]
[b'\xffPX0\x00\x00\x00\x00', 'UPX1', '.rsrc']
```
There doesn't seem to me to be another place to handle the decoding issue and/or to avoid the type problem. The section Name property is resolved lazily via magic methods which then call vstruct primitives vsGetValue. And, consumers of pe.getSections don't have another way afaict to fetch the Name bytes without triggering the issue in the __getattr__ call. That's why I think to handle these weird cases, we should just get bytes back. Other libs do return bytes for section names, so there is some precedent.

**Comment by rakuy0** [comment]
So I would recommend using the `PE.peFromFileName` API, because it handles what I think is the problem here. 

Due to python 3 separating the types of `bytes` and `str` to two completely separate types (instead of in python 2 where they were synonymous with each other), all files that vivisect operates on have to be opened with the `b` flag enabled. So in this case, you should be able to change this line:
`pe_fd = open(sys.argv[1])`
To this:
`pe_fd = open(sys.argv[1], 'rb')`

And everything should work properly, because the `IMAGE_SECTION_NAME` struct in vstruct defines the name as a `v_str`, which when `vsGetValue` is called for the name, decodes it int a utf-8 string.

So try that fix out for your script and lemme know how it goes.

**Comment by mmaps** [comment]
> vstruct defines the name as a v_str, which when vsGetValue is called for the name, decodes it int a utf-8 string

This is exactly the issue, though, isn't it? We can't decode this into a string:
```
>>> b"\xfftext".decode("utf-8")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

I observe the same result when explicitly opening in binary read:
```
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PE
>>> fin=open("test.exe", "rb")
>>> pe=PE.PE(fin)
>>> print([s.Name for s in pe.getSections()])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <listcomp>
  File "/tmp/venv/lib/python3.8/site-packages/vstruct/__init__.py", line 420, in __getattr__
    return r.vsGetValue()
  File "/tmp/venv/lib/python3.8/site-packages/vstruct/primitives.py", line 618, in vsGetValue
    s = self._vs_value.split(b'\x00')[0].decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by williballenthin** [comment]
> That's why I think to handle these weird cases, we should just get bytes back

From a correctness perspective, I think I prefer this solution, as well. @mmaps demonstrates that invalid "strings" can be placed into section names and the Windows loader doesn't care, so we probably can't make any assumptions about the content of this field. 

Downsides:
  - its not as convenient to render, but we could add a `section.getBestName()` method
  - its a breaking change

**Comment by mmaps** [comment]
> Which binary is that one?
The wrong one. :)

Sorry about that, I uploaded the emoji case that I was messing around with. [This is the actual error program](https://github.com/mmaps/HelloSection/blob/main/HelloSection-err.exe). When executed it will print "text" i/o ".text" (or i/o of ☺).

**Comment by rakuy0** [comment]
I believe this is fixed?
