### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by mr-tz** [vivisect/vivisect#509]
https://www.virustotal.com/gui/file/f8e21a5c8a4e366243249c19538ed717ef401f1acfa7578cb6b5609660a19dce/details
```
vivbin -B tests/data/malware/f5aa018daa34809da455a86336f23331
Traceback (most recent call last):
  File "Scripts\vivbin-script.py", line 33, in <module>
    sys.exit(load_entry_point('vivisect', 'console_scripts', 'vivbin')())
  File "vivisect\vivisect\vivbin.py", line 98, in main
    vw.loadFromFile(fname, fmtname=args.parsemod)
  File "vivisect\vivisect\__init__.py", line 2765, in loadFromFile
    fname = mod.parseFile(self, filename=filename, baseaddr=baseaddr)
  File "vivisect\vivisect\parsers\pe.py", line 37, in parseFile
    return loadPeIntoWorkspace(vw, pe, filename=filename, baseaddr=baseaddr)
  File "vivisect\vivisect\parsers\pe.py", line 270, in loadPeIntoWorkspace
    secname = sec.Name.strip("\x00")
  File "vivisect\vstruct\__init__.py", line 420, in __getattr__
    return r.vsGetValue()
  File "vivisect\vstruct\primitives.py", line 618, in vsGetValue
    s = self._vs_value.split(b'\x00')[0].decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xdc in position 0: invalid continuation byte
```

**Comment by williballenthin** [comment]
this may be a dup of #499

**Comment by rakuy0** [comment]
Yea, same. My gut says this is related to #499, but I don't have this binary on hand to double check. Lemme fix that one and then circle back to this to see if that clears the problem up.

**Comment by rakuy0** [comment]
Been a little bit, but did #514 fix this for you @mr-tz?

**Comment by mr-tz** [comment]
Yes, this is fixed now. Thank you!
