### ISSUE TITLE
Pip install vivisect[gui] errors out on windows

### ISSUE THREAD

**Issue by TomSomerville** [vivisect/vivisect#538]
When trying to install vivisect[gui] on windows 11 Pro and windows 11 Enterprise via `pip install vivisect[gui]`, the install fails during the 'preparing metadata (pyproject.toml)' step. Full install text from a fresh Windows 11 install below.

PS C:\Users\User> python --version
Python 3.10.6
PS C:\Users\User> python -m pip --version
pip 22.2.1 from C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\pip (python 3.10)
PS C:\Users\User> pip install vivisect[gui]
Collecting vivisect[gui]
  Downloading vivisect-1.0.8-py3-none-any.whl (4.2 MB)
     ---------------------------------------- 4.2/4.2 MB 14.0 MB/s eta 0:00:00
Collecting pycparser>=2.20
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
     ---------------------------------------- 118.7/118.7 kB 6.8 MB/s eta 0:00:00
Collecting cxxfilt<0.3.0,>=0.2.1
  Downloading cxxfilt-0.2.2-py2.py3-none-any.whl (3.9 kB)
Collecting pyasn1<0.5.0,>=0.4.5
  Downloading pyasn1-0.4.8-py2.py3-none-any.whl (77 kB)
     ---------------------------------------- 77.1/77.1 kB ? eta 0:00:00
Collecting pyasn1-modules<0.3.0,>=0.2.4
  Downloading pyasn1_modules-0.2.8-py2.py3-none-any.whl (155 kB)
     ---------------------------------------- 155.3/155.3 kB ? eta 0:00:00
Collecting msgpack<1.1.0,>=1.0.0
  Downloading msgpack-1.0.4-cp310-cp310-win_amd64.whl (61 kB)
     ---------------------------------------- 61.3/61.3 kB ? eta 0:00:00
Collecting pyqt5==5.15.1
  Downloading PyQt5-5.15.1.tar.gz (3.3 MB)
     ---------------------------------------- 3.3/3.3 MB 26.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
 
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [29 lines of output]
      Traceback (most recent call last):
        File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 156, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
 
      During handling of the above exception, another exception occurred:
 
      Traceback (most recent call last):
        File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 160, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-b6fd2tnt\overlay\Lib\site-packages\sipbuild\api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-b6fd2tnt\overlay\Lib\site-packages\sipbuild\abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-b6fd2tnt\overlay\Lib\site-packages\sipbuild\project.py", line 584, in setup
          self.apply_user_defaults(tool)
        File "C:\Users\User\AppData\Local\Temp\pip-install-mk03oxh7\pyqt5_f6c33d6e78a7445090d170531639feb9\project.py", line 64, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-b6fd2tnt\overlay\Lib\site-packages\pyqtbuild\project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-b6fd2tnt\overlay\Lib\site-packages\sipbuild\project.py", line 236, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-b6fd2tnt\overlay\Lib\site-packages\pyqtbuild\builder.py", line 67, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]
 
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
 
× Encountered error while generating package metadata.
╰─> See above for output.
 
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
 
[notice] A new release of pip available: 22.2.1 -> 22.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip
PS C:\Users\User>

**Comment by rakuy0** [comment]
Hmm. That's weird. I'll pull down a windows 11 vm later tonight to see what's going on. Some QT binary might not be being built/pulled down on windows. That's my current working theory at least.

**Comment by TomSomerville** [comment]
So looking at this error again, it appears that the version installed via pip != main currently. 
When I install via pip, install crashes on Collecting pyqt5==5.15.1

Main has pyqt5==5.15.7 in the setup file.

If I clone main > `cd ./vivisect/` > `pip install -e .[gui]`

install completes fine, and vivbin executes without issue.

If I `pip uninstall vivisect` > `cd  ~` > and then `pip install vivisect[gui]

install is back to pyqt5==5.15.1 and install crashes.


I THINK updating what is available in pip should fix the issue?

**Comment by x00tox01** [comment]
When trying to PIP install vivisect[gui] on windows 10 x64 bit.
I am also getting same issue. 
WHILE I am able to successfully install the PyQt==5.15.7 (latest) but not PyQt==5.15.1.

**Comment by rakuy0** [comment]
So I think you're getting the same issue because I haven't had a chance to cut another release. I wanted to get #551 knocked out via the open PR, but real life stuff came up in December so that's taken longer than anticipated. Once that's in we can cut 1.1.0 since it's been far too long since a proper release and that should fix this issue for people installing things.

**Comment by rakuy0** [comment]
Should be fixed in v1.1.0
