### ISSUE TITLE
ELF: struct.error: unpack_from requires a buffer of at least 2176 bytes for unpacking 2176 bytes at offset 0 (actual buffer size is 0)

### ISSUE THREAD

**Issue by mr-tz** [vivisect/vivisect#585]
```
vivbin -B -vvv 32b2b19f1c6f181ab24e677f7308fb30370608be089006c1a6785cd20cf41161.mal_
2023-02-28 11:44:23,322:INFO:Elf: self._parsePheaders[__init__.py:__init__:104]
2023-02-28 11:44:23,324:INFO:Elf: self._parseDynLinkInfo[__init__.py:__init__:106]
2023-02-28 11:44:23,324:INFO:Elf: self._parseSections[__init__.py:__init__:109]
Traceback (most recent call last):
  File "...Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "...Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "...Scripts\vivbin.exe\__main__.py", line 7, in <module>
  File "...lib\site-packages\vivisect\vivbin.py", line 103, in main
    vw.loadFromFile(fname, fmtname=args.parsemod)
  File "...lib\site-packages\vivisect\__init__.py", line 2822, in loadFromFile
    fname = mod.parseFile(self, filename=filename, baseaddr=baseaddr)
  File "...lib\site-packages\vivisect\parsers\elf.py", line 31, in parseFile
    elf = Elf.Elf(fd)
  File "...lib\site-packages\Elf\__init__.py", line 110, in __init__
    self._parseSections()
  File "...lib\site-packages\Elf\__init__.py", line 189, in _parseSections
    vstruct.VArray(elems=secs).vsParse(secbytes, fast=True)
  File "...lib\site-packages\vstruct\__init__.py", line 174, in vsParse
    values = struct.unpack_from( self._vs_fastfmt, sbytes, offset )
struct.error: unpack_from requires a buffer of at least 2176 bytes for unpacking 2176 bytes at offset 0 (actual buffer size is 0)
```

**Comment by mr-tz** [comment]
I'm not, but am happy to provide insight if I can here (which I doubt as I'm not an expert on ELFs).

**Comment by atlas0fd00m** [comment]
hey @mr-tz ,
just merged in #592, which i think should help with *part* of this.  i believe there was more to it, but wanted to see if this made any difference for you on this issue.

thanks!
@

**Comment by mr-tz** [comment]
Great, thank you. I can test this probably next week and will report back.

**Comment by mr-tz** [comment]
I've confirmed that vivisect doesn't crash on the file anymore. The file may be corrupt (IDA has a bunch or issues with it) so I would consider this fixed here.
