### ISSUE TITLE
ELF SPARC Architecture Support

### ISSUE THREAD

**Issue by schrodyn** [vivisect/vivisect#595]
I'd love to see SPARC supported by vivisect.

```
$ pip freeze | grep vivisect
vivisect==1.1.0
$ file f4df56203a37706c9e224f29b960dc21
f4df56203a37706c9e224f29b960dc21: ELF 32-bit MSB executable, SPARC, version 1 (SYSV), dynamically linked, interpreter /usr/lib/ld.so.1, stripped
$ vivbin -B f4df56203a37706c9e224f29b960dc21
Traceback (most recent call last):
  File "/Users/user/.venv/arcadia/bin/vivbin", line 8, in <module>
    sys.exit(main())
  File "/Users/user/.venv/arcadia/lib/python3.10/site-packages/vivisect/vivbin.py", line 98, in main
    vw.loadFromFile(fname, fmtname=args.parsemod)
  File "/Users/user/.venv/arcadia/lib/python3.10/site-packages/vivisect/__init__.py", line 2786, in loadFromFile
    fname = mod.parseFile(self, filename=filename, baseaddr=baseaddr)
  File "/Users/user/.venv/arcadia/lib/python3.10/site-packages/vivisect/parsers/elf.py", line 31, in parseFile
    return loadElfIntoWorkspace(vw, elf, filename=filename, baseaddr=baseaddr)
  File "/Users/user/.venv/arcadia/lib/python3.10/site-packages/vivisect/parsers/elf.py", line 144, in loadElfIntoWorkspace
    raise Exception("Unsupported Architecture: %d\n", elf.e_machine)
Exception: ('Unsupported Architecture: %d\n', 2)
```

**Comment by atlas0fd00m** [comment]
thank you for voicing your wish!
we have an open branch for SPARC (along with a half dozen other architectures), and we're always interested in how we can better prioritize the loads of work we're always juggling.

*we'd love help!*  whether it's testing and troubleshooting, or implementing emulation and symbolik code, or helping turn out support for either 64-bit or V9 architectures.  consider working with us so it's sure to meet your needs :)

check this out:
   https://github.com/vivisect/vivisect/pull/568
