### ISSUE TITLE
archId not available for ARMv7A

### ISSUE THREAD

**Issue by jpsnyder** [vivisect/vivisect#666]
When the architecture name is "ARMv7A", the arch constant is unable to be detected using `vw.arch.getArchId()`.

```fish
(vivisect) jon@fluffy ~/d/vivisect > file strings_arm                                                                           3.977s
strings_arm: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.3, BuildID[sha1]=36f857a4e75f227a253c7c70886a00cf51cc732d, for GNU/Linux 3.2.0, not stripped

(vivisect) jon@fluffy ~/d/vivisect > bpython                                                                                  288.314s
bpython version 0.24 on top of Python 3.12.4 /home/jon/.local/share/virtualenvs/vivisect-9xCeL38c/bin/python
>>> import vivisect
>>> vw = vivisect.VivWorkspace()
>>> vw.loadFromFile("strings_arm")
...
>>> vw.analyze()
...
>>> vw.arch.getArchId() is None
True
```

:imp: :imp: :imp:

**Comment by atlas0fd00m** [comment]
see #668 

i'm just gonna label this the SatanBug

**Comment by atlas0fd00m** [comment]
sorry!  i didn't realize you submitted a PR or i would have just used that...

**Comment by jpsnyder** [comment]
No worries, just care about it being fixed. :)

**Comment by jpsnyder** [comment]
Also, unrelated, but I do run into errors analyzing my file. 
It is trying to emulate `uhsaxvc`, but that address is actually suppose to be data not code.

```
0x102d4: opval=0x21008: brflags is BR_DEREF, but loctup is None.  Don't know what to do. skipping.  taint:None ('None')
0x102bc: FAIL: could not resolve name for 0x0.  Skipping.
PLT: 0x1030c - Could not find a branch!
Error emulating function 0x102c8
        []
Traceback (most recent call last):
  File "/home/jon/dev/vivisect/vivisect/analysis/arm/thunk_reg.py", line 109, in analyzeFunction
    emu.runFunction(fva, maxhit=1)
  File "/home/jon/dev/vivisect/vivisect/impemu/platarch/arm.py", line 298, in runFunction
    raise e
  File "/home/jon/dev/vivisect/vivisect/impemu/platarch/arm.py", line 239, in runFunction
    self.executeOpcode(op)
  File "/home/jon/dev/vivisect/envi/archs/arm/emu.py", line 348, in executeOpcode
    raise envi.UnsupportedInstruction(self, op)
envi.exc.UnsupportedInstruction: Unsupported Instruction: 0x00021038 uhsaxvc r6, r1, r6
0x102d4: opval=0x21008: brflags is BR_DEREF, but loctup is None.  Don't know what to do. skipping.  taint:None ('None')
0x102c8: FAIL: could not resolve name for 0x0.  Skipping.
Error in PLT-late analysis: TypeError("'NoneType' object is not iterable")
Traceback (most recent call last):
  File "/home/jon/dev/vivisect/vivisect/analysis/elf/elfplt_late.py", line 31, in analyze
    analyzePLT(vw, pltva, pltsz)
  File "/home/jon/dev/vivisect/vivisect/analysis/elf/elfplt_late.py", line 106, in analyzePLT
    fillPLTviaGOTXrefs(vw, jmpheur, pltva, pltsz)
  File "/home/jon/dev/vivisect/vivisect/analysis/elf/elfplt_late.py", line 149, in fillPLTviaGOTXrefs
    if isGOT(vw, xrto):
       ^^^^^^^^^^^^^^^
  File "/home/jon/dev/vivisect/vivisect/analysis/elf/elfplt_late.py", line 318, in isGOT
    for gotva, gotsz in gots.get(fname):
TypeError: 'NoneType' object is not iterable
_getNameParts('__TMC_END__'): fname is None (and shouldn't be)
_getNameParts('__TMC_END__'): fname is None (and shouldn't be)
```

Let me know if you would like me to create a separate issue.

**Comment by atlas0fd00m** [comment]
yes, thank you for that.  please create a separate issue, just for better tracking down the road.
